# Generated by Django 2.1a1 on 2018-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180607_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
